### ISSUE TITLE
Capitalization Issue

### ISSUE THREAD

**Issue by MrSpore** [Metastruct/garrysmod-chatsounds#64]
Recently i submitted a PullRequest of which was merged, attempting to change its capital letters results in weird results, SpiralP also had this problem where it wont recognize the letter changes and often deletes them.

**Comment by TrenchFroast** [comment]
thats because changing the capitalization doesnt count as a change unless really specific settings are changed

**Comment by AgentWhatever** [comment]
On what OS are you having capitalisation issues with git?

**Comment by MrSpore** [comment]
I was using Windows 10. Not sure what os spiral was using.

**Comment by AgentWhatever** [comment]
Then there is this very simple fix i found out litterally yesterday
Go to your chatsounds root folder, open up .git/config with a text editor and set the capitalization setting to... uh... whatever it needs to be. And voila

**Comment by SpiralP** [comment]
tried setting that ignorecase to false, still no good

**Comment by SpiralP** [comment]
I think it was throwing me off since github has trouble showing caps changes

for example files like `AALLAALLAALL.ogg` show up lowercase in AgentWhatever's commit to fix caps in
https://github.com/Metastruct/garrysmod-chatsounds/commit/ca80a0b802e2b0251632eccfed4d943d13b49d01
but not in the listing in
https://github.com/Metastruct/garrysmod-chatsounds/commits/master/sound/chatsounds/autoadd/vsaucepoop/AALLAALLAALL.ogg

**Comment by PotcFdk** [comment]
The preprocessor now warns about paths that contain uppercase characters and will not integrate them into the lists anymore. At least now you shouldn't be able to accidentally add uppercase sound files.
